name: DevOps Terminator CI-CD

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Clonar codigo fuente
      uses: actions/checkout@v4

    - name: Ejecutar pruebas de seguridad (SAST)
      run: |
        echo "Iniciando analisis de codigo con TERMINATOR..."
        echo "Validando estructura de index.html..."
        echo "Analisis completado exitosamente."

    - name: Estado del despliegue (CD)
      run: echo "El codigo es seguro. Despliegue autorizado."
